packages:
  # all packages in subdirs of packages/
  - 'packages/**'
  # all packages in subdirs of apps/
  - 'apps/**'
  # exclude packages that are inside test directories (conflicto con lerna)
  #- '!**/test/**'