# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: database
    ports: 
      - 7052:3306  
